[".local/bin/chezmoi"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "twpayne/chezmoi" (printf "chezmoi_*_linux_amd64.tar.gz") | quote }}
executable = true
refreshPeriod = "168h"
path = "chezmoi"

[".local/bin/hugo"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL 
         "gohugoio/hugo" 
         (printf "hugo_extended_*_%s-%s.tar.gz" 
         .chezmoi.os .chezmoi.arch) | 
         quote }}
executable = true
refreshPeriod = "168h"
path = "hugo"

[".local/bin/eza"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "eza-community/eza" "eza_x86_64-unknown-linux-gnu.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "./eza"

[".oh-my-zsh-custom/completions/_eza"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "eza-community/eza" "completions-*.tar.gz" | quote }}
refreshPeriod = "168h"
stripComponents = 3
path = "_eza"

[".local/bin/atuin"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "atuinsh/atuin" "atuin-x86_64-unknown-linux-gnu.tar.gz" | quote }}
refreshPeriod = "168h"
stripComponents = 1
path = "atuin"

[".local/bin/nerdctl"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "containerd/nerdctl" (printf "nerdctl-*-linux-amd64.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
path = "nerdctl"

[".local/bin/lazygit"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" (printf "lazygit_*_linux_x86_64.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
path = "lazygit"

[".local/bin/k9s"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "derailed/k9s" "k9s_Linux_amd64.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "k9s"

[".local/bin/kubens"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "ahmetb/kubectx" (printf "kubens_*_linux_x86_64.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
path = "kubens"

[".local/bin/kubectx"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "ahmetb/kubectx" (printf "kubectx_*_linux_x86_64.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
path = "kubectx"

[".local/bin/trivy"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "aquasecurity/trivy" (printf "trivy_*_Linux-64bit.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
path = "trivy"

[".local/bin/dive"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "wagoodman/dive" (printf "dive_*_linux_amd64.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
path = "dive"

[".local/bin/stylua"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "JohnnyMorganz/StyLua" "stylua-linux-x86_64.zip" | quote }}
refreshPeriod = "168h"
executable = true
path = "stylua"

{{- $helmVersion := ((gitHubLatestRelease "helm/helm").TagName) | replaceAllRegex "v" "" }}
[".local/bin/helm"]
type = "archive-file"
refreshPeriod = "168h"
url = "https://get.helm.sh/helm-v{{ $helmVersion }}-linux-amd64.tar.gz"
stripComponents = 1
path = "helm"

[".local/bin/hubble"]
type = "archive-file"
executable = true
refreshPeriod = "720h"
url = {{ gitHubLatestReleaseAssetURL "cilium/hubble" "hubble-linux-amd64.tar.gz" | quote }}
path = "hubble"

[".local/bin/cilium"]
type = "archive-file"
executable = true
refreshPeriod = "720h"
url = {{ gitHubLatestReleaseAssetURL "cilium/cilium-cli" "cilium-linux-amd64.tar.gz" | quote }}
path = "cilium"

[".local/bin/ltrs"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "jeertmans/languagetool-rust" (printf "ltrs-v*-x86_64-unknown-linux-musl.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
stripComponents = 1
path = "ltrs"

[".local/bin/vale"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "errata-ai/vale" (printf "vale_*_Linux_64-bit.tar.gz") | quote }}
refreshPeriod = "168h"
executable = true
path = "vale"

[".local/bin/starship"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "starship/starship" "starship-i686-unknown-linux-musl.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "starship"

[".local/bin/typst"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "typst/typst" "typst-x86_64-unknown-linux-musl.tar.xz" | quote }}
refreshPeriod = "168h"
executable = true
stripComponents = 1
path = "typst"

[".local/bin/todo.sh"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "todotxt/todo.txt-cli" "todo.txt_cli-*.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
stripComponents = 1
path = "todo.sh"

[".local/bin/uv"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "astral-sh/uv" "uv-x86_64-unknown-linux-gnu.tar.gz" | quote }}
refreshPeriod = "168h"
stripComponents = 1
executable = true
exact = true
path = "uv"

[".local/bin/uvx"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "astral-sh/uv" "uv-x86_64-unknown-linux-gnu.tar.gz" | quote }}
refreshPeriod = "168h"
stripComponents = 1
executable = true
exact = true
path = "uvx"

[".local/bin/helmfile"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "helmfile/helmfile" "helmfile_*_linux_amd64.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "helmfile"

[".local/bin/yazi"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "sxyazi/yazi" "yazi-x86_64-unknown-linux-gnu.zip" | quote }}
refreshPeriod = "168h"
executable = true
stripComponents = 1
path = "yazi"

[".local/bin/ya"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "sxyazi/yazi" "yazi-x86_64-unknown-linux-gnu.zip" | quote }}
refreshPeriod = "168h"
executable = true
stripComponents = 1
path = "ya"

[".local/bin/lychee"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "lycheeverse/lychee" "lychee-x86_64-unknown-linux-gnu.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "lychee"

[".local/bin/stern"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "stern/stern" "stern_*_linux_amd64.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "stern"

[".local/bin/popeye"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "derailed/popeye" "popeye_linux_amd64.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "popeye"

[".local/bin/gron"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "tomnomnom/gron" "gron-linux-amd64-*.tgz" | quote }}
refreshPeriod = "168h"
executable = true
path = "gron"

[".local/bin/ttdl"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "VladimirMarkelov/ttdl" "ttdl_*_linux-x64-musl.tar.gz" | quote }}
refreshPeriod = "168h"
executable = true
path = "ttdl"

[".local/bin/bw"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "bitwarden/client" "bw-linux-*.zip" | quote }}
refreshPeriod = "168h"
executable = true
path = "bw"
